---
- name: personal-playbook | docker install
  hosts: localhost
  connection: local
  become: yes
  user: thulana
  become_user: root
  become_method: sudo
  vars_files:
      - vars/docker_install.yml
  roles:
    - Docker
