#- debug: var={{ sftp_config }}
#- include: ssh_config.yml
#  when: sftp_config

- include: docker_install.yml
  when: docker_install == true

- include: docker_cleanup.yml
  when: docker_cleanup == true


